//
//  ParamKeyString.h
//  iCars
//
//  Created by xuhu on 14-9-23.
//  Copyright (c) 2014年 zciot. All rights reserved.
//

#import <Foundation/Foundation.h>

#define KEY_FIRST_INTO                  @"firstInto"        //第一次进入程序

#define CITY @"city"
#define IMEI @"imei"
#define TYPE @"type"
#define MSGCODE @"msgCode"
#define CITIES @"cities"
#define ID @"id"
#define NAME @"name"
#define AREACODE @"areaCode"
#define PID @"pid"
#define PHONE @"phone"
#define SEX @"sex"
#define AGE @"age"
#define DRIVINGLICENCE @"drivingLicence"
#define QQ @"qq"
#define SERVICEPASSWORD @"servicePassword"
#define RESULT @"result"
#define CARNO @"carNo"
#define KINSFOLKPHONE @"kinsfolkPhone"
#define STATUS @"status"

//主页信息类KEY
#define MILEAGE @"mileage"
#define MILEAGEKEEP @"mileageKeep"
#define LASTDATE @"lastDate"
#define CHANNELPHONE @"channelPhone"
#define CARBID @"carbid"
#define CARBNAME @"carBName"
#define CARBURL @"carBUrl"
#define CARSID @"carsid"
#define CARSNAME @"carSName"
#define CARSTYPEURL @"carSTypeUrl"
#define CARTYPEID @"carTypeId"
#define CARTYPENAME @"carTypeName"
#define CARTYPEURL @"carTypeUrl"
#define SCORE @"score"
#define WARRANTYNO @"warrantyNo"
#define COLOR @"color"
#define ENGINECODE @"engineCode"
#define SIGNCODE @"signCode"

#define ISCHILD @"ischild"
#define CHILD @"child"
#define KEYS @"keys"
#define CARS @"cars"
#define DICTS @"dicts"

#define ACC @"acc"
#define LON @"lon"
#define LAN @"lan"
#define SPEED @"speed"
#define DIRECTION @"direction"
#define TIME @"time"
#define GPSNUM @"gpsNum"
#define GSM @"gsm"

//OBDDTO KEY
#define CS @"cs"
#define FDJZS @"fdjzs"
#define SW @"sw"
#define DPDY @"dpdy"
#define YXZT @"yxzt"
#define LC @"lc"
#define YH @"yh"
#define FDJFH @"fdjfh"
#define JQMKD @"jqmkd"
#define BGLYH @"bglyh"
#define XSSJ @"xssj"

#define CODE @"code"
#define ANALYSE @"analyse"
#define SUGGEST @"suggest"
#define REMARK @"remark"

#define FDJLQYWD @"fdjlqywd"
#define JQWD @"jqwd"
#define KQLL @"kqll"
#define JQMJDWZ @"jqmjdwz"
#define KZMKDY @"kzmkdy"
#define HJWD @"hjwd"
#define QGDHTQJ @"qgdhtqj"
#define JQQGJDYL @"jqqgjdyl"
#define MILDLHXSJL @"mildlhxsjl"
#define QCGZMNJCS @"qcgzmnjcs"
#define QCGZMXSJL @"qcgzmxsjl"
#define GZZSDLYZSJ @"gzzsdlyzsj"
#define QCGZMFDJYZSJ @"qcgzmfdjyzsj"
#define FDJRYL @"fdjryl"
#define BCPFYQ @"bcpfyq"

#define IDS @"ids"
#define STARTTIME @"startTime"
#define ENDTIME @"endTime"
#define SMSSTATUS @"smsStatus"
#define CYCLE @"cycle"
#define TIMING @"timing"
#define PAST @"past"
#define DEFENCENAME @"defenceName"
#define ADDRESS @"address"

#define TODAY @"today"
#define TOMORROW @"tomorrow"

#define RATEDSTATUS @"ratedStatus"
#define RATEDSPEED @"ratedSpeed"
#define VOICESTATUS @"voiceStatus"

#define CF @"cf"、
#define PZ @"pz"
#define DPDDY @"dpddy"
#define TC @"tc"
#define DD @"dd"
#define TDLB @"tdlb"
#define PLJS @"pljs"
#define DEFENCES @"defences"
#define URGENCYMESSAGE @"urgencyMessage"
#define ALARMTIME @"alarmTime"
#define ELECTRONICFENCE @"electronicFence"

#define REMINDSTATUS @"remindStatus"
#define LOCAINFOSTATUS @"locainfoStatus"
#define TITLE @"title"
#define VERSION @"version"
#define TRACKVIEWURL @"trackViewUrl"
#define VOICE @"voice"
#define VELOCTITY @"veloctity"
#define WEATHERSWITCH @"weatherSwitch"
